feature: Add users page and change profile-detail page data.
maaxnikitin94/angular-task pull request #1
Opened 2022-08-15 12:16 UTC by maaxnikitin94

2022-08-16 12:01 UTC, DzmVasileusky requested changes

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/features.module.ts
> +import { CommonModule } from '@angular/common';
When you are working on the existing project you need to preserve the code style.
Usually there are styleguides, we have them as well.
It sometimes hard to keep them in head so you should be attentive.

Look how imports are organised in all the files. They are sorted alphabetically. You need to do the same.
There are IDE features and plugin which can help you.

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/home-page/home-page.component.scss
> +}
keep your code style clean, do not rush

first blocks has an empty line break, 2-3 - no
you need to keep it consistent.

same for a bracket after a selector, check how it was written above, space before bracket. It is hard to read when there is no spaces

same for space after `:`

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/home-page/home-page.component.scss
> +.users-link:hover{
it is `scss`, start reading docs about its features

```
.users-link {
  &:hover {}
}
```

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/profile/profile-detail/profile-detail.component.html
> +    <mat-card *ngIf="(user$ | async)[0] as user" class="card">
`user` means 1 user, it can't be an array of users, if you need to get first user - do it in class not in the template

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/profile/profile-detail/profile-detail.component.ts
> +    public user$: Observable<any>;
never use `any` when you know the type
`any` can be used only in one case: when it literally can be "anything"
is user data anything? or something with known set of properties? think about it

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/profile/profile-detail/profile-detail.component.ts
> +        .pipe(map((value) => Object.values(value).slice(0, -1).filter((val: any) => val.id.name === id)));
break down on different lines methods chains to improve readability

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/profile/profile-detail/profile-detail.component.ts
>          this.store.dispatch(profileActions.initProfile());
you need to fetch user data correctly

1. `this.store.dispatch(profileActions.getUser(id));`
2. call `this.userService.getUser(id)` inside ngrx effect subscribed to the action above
3. call ngrx action `profileActions.getUserSuccess(userData)` and set user data in ngrx reducer to the `user` property
4. subscribe to `user` data from ngrx with a selector

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/profile/store/profile.reducers.ts
> +// };
do not leave unused commented code, nobody will understand what had it been left more

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/profile/store/profile.reducers.ts
> +    on(profileActions.initProfile, (state) => (state))
this action is doing nothing now. do not left useless code

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/services/users.service.ts
> +    getUsers () {
and returned type

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/store/users.effects.ts
> +            first(),
why first? what if user will reopen the page?

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/store/users.effects.ts
> +            mergeMap(() =>
better use switchMap here to prevent multiple same requests

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/store/users.actions.ts
> +    props<{ users?: any }>()
no any!

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/store/users.selectors.ts
> +export const getUsersState = createSelector(getUserState, (state: any) => state);
bad naming

`getUserState` and `getUsersState`

1. this two names are looking like at same level but this is not true
2. `getUsersState` usually means that you are getting the whole state object of 'Users' feature, which is not true

you can just do `getUsers` or if you want it to be more clear `getUsersFromState`

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/store/users.selectors.ts
> +export const getUsersState = createSelector(getUserState, (state: any) => state);
no ANY!

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/users-page.component.html
> +<table [width]="'1000px'">
you don't need double quotes for a string value
just 
`width="1000px"`

and you of course shouldn't set static html attribute as Angular binding

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/users-page.component.html
> +        <tr *ngFor="let user of users!">
what is `!` here for?

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/users-page.component.scss
> +}
same things as in previous scss file

2022-08-16 12:01 UTC, DzmVasileusky commented on src/app/features/users-page/users-page.component.ts
> +        this.users$ = this.store.select(getUsersState).pipe(map((value) => Object.values(value).slice(0, -1)));
why are you slicing it?

2022-08-18 11:20 UTC, DzmVasileusky requested changes

2022-08-18 11:20 UTC, DzmVasileusky commented on src/app/features/users-page/store/users.reducers.ts
> +    on(getUsersSuccess, (state, users) => users)
you should update user property of state
```
=> { ...state, users }
```

2022-08-22 14:02 UTC, DzmVasileusky requested changes

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/features.module.ts
> +        CommonModule
sort alpha pls

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/home-page/home-page.component.html
> +    <div style="text-align: center">
never use inline style, this is a bad practice
create a stylesheet and set through it

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/profile/interfaces/profile-state.ts
> +import { IProfile } from '@features/profile/interfaces/profile';
this project already has interfaces, you should always follow the same code style
Interfaces here doesn't have `I` prefix so you have to avoid it as well (that doesn't mean that `I` prefix is bad this is just not in same style)

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/profile/interfaces/profile.ts
> +    picture: { large: string, medium: string, thumbnail: string }
alpha poperties
Alt + Shift + L

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/profile/interfaces/profile.ts
> +        street: { number: number, name: string },
prefer one style of object declarations: if you are doing it multiline, make it multiline here as well
same with props ending, you have both `;` in root object and `,` in other, do the same

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/users-page/services/users.service.ts
> +    getUsers () {
not fixed

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/users-page/services/users.service.ts
> +        .pipe(map(({ results }: any): IUsers[] => results.map((user: any) => ({
no `any`!

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/users-page/services/users.service.ts
> +        .pipe(map(({ results }: any): IProfile => results[0]));
no `any`

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/users-page/users-page.component.html
> +<table style="width: 1000px; border: 1px solid black">
no inline style

2022-08-22 14:02 UTC, DzmVasileusky commented on src/app/features/users-page/users-page.component.html
> +                <a [routerLink]="['/profile/' + user.firstName]">{{ user.firstName }}</a>
if you have links like this with user id you need to emulate a method which get user by id, so rename `getProfile ()` to `getUser (id: string)` and just use id as `seed`

2022-08-23 12:56 UTC, maaxnikitin94 commented on src/app/features/profile/interfaces/profile.ts
> +    picture: { large: string, medium: string, thumbnail: string }
I don't know how to sort it, with which plugin. Alt + Shift+ L don't work in Webstorm.

2022-08-23 13:08 UTC, merged